version: "3.7"
services:
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    ports:
      - "3307:3306"

  ims:
    depends_on:
      - "db"
    build: .
    ports:
      - "3000:3000"
    restart: on-failure
    environment:
      IMS_DATABASE_USERNAME: root
      IMS_DATABASE_PASSWORD: root
      IMS_DATABASE_NAME: ims
      IMS_DATABASE_PORT: 3306
      IMS_DATABASE_HOST: db
      RAILS_ENV: development
      RAILS_MAX_THREADS: 20
    volumes:
      - ".:/app"

volumes:
  db: