require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/employees", type: :request do
  let(:valid_attributes) {
    {name: "name", email: "email@example.com", experience: "8.3"}
  }

  let(:invalid_attributes) {
    {name: "", email: "", experience: ""}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Employee.create! valid_attributes
      get "http://localhost:3000/employees.json"

      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      employee = Employee.create! valid_attributes
      get "http://localhost:3000/employees/#{employee.id}.json"

      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Employee" do
        expect {
          post "http://localhost:3000/employees.json", params: {employee: valid_attributes}
        }.to change(Employee, :count).by(1)
      end
    end

    context "with invalid parameters" do
      it "does not create a new Employee" do
        expect {
          post "http://localhost:3000/employees.json", params: {employee: invalid_attributes}
        }.to change(Employee, :count).by(0)
      end

      it "returns a unprocessable entity status" do
        post "http://localhost:3000/employees.json", params: {employee: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end

    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {name: "naam", email: "naam@example.com", experience: "9.3", dob: "1988-12-10"}
      }

      it "updates the requested employee" do
        employee = Employee.create! valid_attributes
        patch "http://localhost:3000/employees/#{employee.id}.json", params: {employee: new_attributes}
        employee.reload
        expect(response).to be_successful
      end
    end

    context "with invalid parameters" do

      it "returns a unprocessable entity status" do
        employee = Employee.create! valid_attributes
        patch "http://localhost:3000/employees/#{employee.id}.json", params: {employee: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end

    end
  end

end
